# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_auto_20161123_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('key', models.CharField(max_length=30)),
                ('value', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='accountdata',
            unique_together=set([('username', 'key')]),
        ),
    ]
